name: CounterHit
options:
  bundleIdPrefix: com.rmkwz
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: RMM5DYSN43
targets:
  CounterHit:
    type: application
    platform: iOS
    sources:
      - CounterHit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rmkwz.CounterHit
        INFOPLIST_FILE: CounterHit/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: CounterHit/CounterHit.entitlements
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: CounterHitWidget
  CounterHitWidget:
    type: app-extension
    platform: iOS
    sources:
      - CounterHitWidget
      - CounterHit/Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rmkwz.CounterHit.CounterHitWidget
        INFOPLIST_FILE: CounterHitWidget/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: CounterHitWidget/CounterHitWidget.entitlements
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
